java Main best puzzles\test1.txt best1.txt
java Main best puzzles\test2.txt best2.txt
java Main best puzzles\test3.txt best3.txt
java Main best puzzles\test4.txt best4.txt
java Main best puzzles\test5.txt best5.txt
java Main astar puzzles\test1.txt astar1.txt
java Main astar puzzles\test2.txt astar2.txt
java Main astar puzzles\test3.txt astar3.txt
java Main astar puzzles\test4.txt astar4.txt
java Main astar puzzles\test5.txt astar5.txt
java Main depth puzzles\test1.txt depth1.txt
java Main depth puzzles\test2.txt depth2.txt
java Main depth puzzles\test3.txt depth3.txt
java Main depth puzzles\test4.txt depth4.txt
java Main depth puzzles\test5.txt depth5.txt
java Main breadth puzzles\test1.txt breadth1.txt
java Main breadth puzzles\test2.txt breadth2.txt
java Main breadth puzzles\test3.txt breadth3.txt
java Main breadth puzzles\test4.txt breadth4.txt
java Main breadth puzzles\test5.txt breadth5.txt